create table if not exists contacts (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  program text,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists programs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  degree_type text not null,
  duration text not null,
  description text,
  enrolled integer not null default 0,
  color_from text not null default '#064761',
  color_to text not null default '#0b5f82',
  icon text not null default 'fa-graduation-cap',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists applications (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  dob date,
  program_id bigint references programs(id),
  entry_year text,
  qualifications text,
  statement text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(email, program_id)
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  event_date date not null,
  start_time time not null,
  end_time time,
  location text not null,
  description text,
  max_seats integer,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(title, event_date)
);

create table if not exists event_registrations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  name text not null,
  email text not null,
  created_at timestamptz not null default now(),
  unique(event_id, email)
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  content text,
  category text not null,
  author text not null,
  published boolean not null default false,
  published_at date,
  created_at timestamptz not null default now()
);

alter table contacts enable row level security;
alter table newsletter_subscribers enable row level security;
alter table programs enable row level security;
alter table applications enable row level security;
alter table events enable row level security;
alter table event_registrations enable row level security;
alter table news enable row level security;

create policy "Public can read active programs"
  on programs for select
  using (active = true);

create policy "Public can read active events"
  on events for select
  using (active = true);

create policy "Public can read published news"
  on news for select
  using (published = true);
